### PR TITLE
9.4.22.v20191022 upgrade (incoming branch)

### PR DESCRIPTION
**Pull request by jglick**
Replaced from https://github.com/eclipse/jetty.project/tree/jetty-9.4.22.v20191022/jetty-maven-plugin except `Jenkinsfile`.

### CODE REVIEW

**Comment by jglick** [comment]
Not sure about merging into `master` though. `git diff incoming master` shows a bunch of whitespace changes which are likely to cause conflicts. There is an unresolved merge conflict in `JettyRunWarExplodedMojo.java`. And I get a ton of other conflicts (nontrivial content unrelated to Jenkins) which suggest that some previous merge was not done correctly: just `git checkout master && git merge incoming` fails, whereas it ought to have said that everything is already up to date…right? The last genuine merge of `incoming` I see is from @kohsuke in 2016. Looking at #9, it just does not seem to match what the README says is the correct procedure.

**Comment by jglick** [comment]
Perhaps we could just get rid of this fork and use upstream `jetty-maven-plugin` in `jenkinsci/jenkins/war/pom.xml`? From looking at the diff, the only thing we are adding is `MaskingClassLoader` and its usage from `JettyRunMojo`. But the only explanation is that it

> provide[s] isolation between Maven that runs Hudson and Maven that runs inside Hudson.

What is the “Maven that runs inside [Jenkins]” supposed to be? If that is just what used to be `jenkinsci/maven-plugin` before it was split into a plugin, I guess we do not care. In https://github.com/jenkinsci/jenkins/commit/f50b775ddc527da54bffb361a7bbd715acf96746 there is a reference to some `issue #932`, whatever that once was.

(There is also a `JettyRunForkedMojo.getWarArtifacts` which seems to be unused.)

**Comment by jglick** [comment]
If https://github.com/jenkinsci/jenkins/pull/4351 is merged then this PR can be closed and the repository archived.

**Comment by daniel-beck** [comment]
> there is a reference to some `issue #932`, whatever that once was

https://issues.jenkins-ci.org/browse/JENKINS-932 looks good.

**Pull request closed without merging**
