### PR TITLE
Feature/jetty 9.4.5.v20170502

### PR DESCRIPTION
**Pull request by olamy**
Upgrade to jetty_9.4.5.v20170502

### CODE REVIEW

**Comment by jglick** [comment]
Supersedes #4 I suppose?

**Review by jglick — COMMENTED** [review]
Not really reviewable as such.

Is there a reason you know of that we seem to have patched upstream sources, rather than just introducing new mojos that delegate to standard ones with some customizations using supported APIs? Is there some way to get a diff from the vendor branch or whatever?

**Comment by olamy** [comment]
@jglick I was just following instructions coming from the README file.

**Review by oleg-nenashev — APPROVED** [review]
I assume we do not worry about the binary compatibility here, hence 👍

**Comment by oleg-nenashev** [comment]
@olamy Are you able to release it on your own?

**Comment by olamy** [comment]
@oleg-nenashev  this should be fixed with this https://github.com/jenkins-infra/repository-permissions-updater/pull/303  :-)

**Pull request merged**
